# Generated by Django 5.0.6 on 2024-05-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='Password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
